### ISSUE TITLE
Docker client/server version mismatch crashing cli

### ISSUE THREAD

**Issue by amjith** [j-bennet/dockercli#27]
```
/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/Users/amjith/.virtualenvs/dockercli/bin/dockercli", line 9, in <module>
    load_entry_point('dockercli==0.1', 'console_scripts', 'dockercli')()
  File "/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/amjith/Dropbox/code/python/dockercli/dockercli/main.py", line 178, in cli
    dockercli.run_cli()
  File "/Users/amjith/Dropbox/code/python/dockercli/dockercli/main.py", line 154, in run_cli
    output = self.handler.handle_input(document.text)
  File "/Users/amjith/Dropbox/code/python/dockercli/dockercli/client.py", line 162, in handle_input
    return handler(None, None)
  File "/Users/amjith/Dropbox/code/python/dockercli/dockercli/client.py", line 111, in containers
    csdict = self.truncate_rows(self.instance.containers(**kwargs))
  File "/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/docker/client.py", line 423, in containers
    res = self._result(self._get(u, params=params), True)
  File "/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/docker/client.py", line 123, in _result
    self._raise_for_status(response)
  File "/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/docker/client.py", line 119, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.17, server: 1.15)")
```

**Comment by j-bennet** [comment]
Fixed with 1d92b9d47b9c6ab6839bdc370e41764560454808.
