### ISSUE TITLE
Typing 'ps' crashes dockercli

### ISSUE THREAD

**Issue by amjith** [j-bennet/dockercli#59]
This is running on latest HEAD of master. 

I have one container running that was started from the shell. I've pasted the output of `docker ps` at the bottom.

```
Version: 0.2
Home: http://dockercli.com
dockercli> ps
Traceback (most recent call last):
  File "/Users/amjith/.virtualenvs/dockercli/bin/dockercli", line 9, in <module>
    load_entry_point('dockercli==0.2', 'console_scripts', 'dockercli')()
  File "/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/amjith/.virtualenvs/dockercli/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/amjith/Dropbox/code/python/dockercli/dockercli/main.py", line 258, in cli
    dockercli.run_cli()
  File "/Users/amjith/Dropbox/code/python/dockercli/dockercli/main.py", line 218, in run_cli
    self.handler.output)
  File "/Users/amjith/Dropbox/code/python/dockercli/dockercli/formatter.py", line 162, in format_data
    data = flatten_rows(data)
  File "/Users/amjith/Dropbox/code/python/dockercli/dockercli/formatter.py", line 255, in flatten_rows
    row[k] = ', '.join(row[k])
TypeError: sequence item 0: expected string or Unicode, dict found
```

Running `docker ps`
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
1e05f4b057eb        mariadb:latest      "/docker-entrypoint.   2 minutes ago       Up 2 minutes        3306/tcp            some-mariadb
```

**Comment by j-bennet** [comment]
Should be fixed now; at least, I tested with the same container and it works.

**Comment by amjith** [comment]
Fixed!
